---
- name: setup tomcat
  hosts: all
  become: true
  tasks: 
  - name: Update apt package cache
    apt: 
     update_cache: yes
  - name: install java on ubuntu
    apt: 
      name: openjdk-11-jre-headless
      state: present
    when: ansible_os_family == "Debian"
  - name: download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.25/bin/apache-tomcat-10.1.25.tar.gz
      dest: /opt

  - name: untar apache packages
    unarchive:
      src: /opt/apache-tomcat-10.1.25.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permissions on startup.sh file
    file: 
      path: /opt/apache-tomcat-10.1.25/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-10.1.25/bin    

  